/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugastiga;

/**
 *
 * @author iman
 */
public class TugasTigaForm extends javax.swing.JFrame {

    /**
     * Creates new form TugasTigaForm
     */
    public TugasTigaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup bgJenisKelamin = new javax.swing.ButtonGroup();
        txtNama = new javax.swing.JTextField();
        txtLahir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrLaki = new javax.swing.JRadioButton();
        jrPer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbOlahraga = new javax.swing.JCheckBox();
        cbJalan = new javax.swing.JCheckBox();
        cbBaca = new javax.swing.JCheckBox();
        cbTidur = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHasil = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("TTL");

        bgJenisKelamin.add(jrLaki);
        jrLaki.setText("Laki - Laki");
        jrLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrLakiActionPerformed(evt);
            }
        });

        bgJenisKelamin.add(jrPer);
        jrPer.setText("Perempuan");
        jrPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPerActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Hobi");

        cbOlahraga.setText("Olahraga");

        cbJalan.setText("Jalan - jalan");

        cbBaca.setText("Membaca");

        cbTidur.setText("Tidur");

        textHasil.setColumns(20);
        textHasil.setRows(5);
        jScrollPane1.setViewportView(textHasil);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrLaki)
                        .addGap(18, 18, 18)
                        .addComponent(jrPer))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNama)
                        .addComponent(txtLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbOlahraga)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJalan)
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbTidur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1))
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrLaki)
                            .addComponent(jrPer)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbOlahraga)
                            .addComponent(cbBaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJalan)
                            .addComponent(cbTidur))))
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrLakiActionPerformed
        // TODO add your handling code here:
        //if(jrLaki.isSelected()) {
        //    textHasil.setText(jrLaki.getText());
        //}
    }//GEN-LAST:event_jrLakiActionPerformed

    private void jrPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPerActionPerformed
        // TODO add your handling code here:
        //if(jrPer.isSelected()) {
        //    textHasil.setText(jrPer.getText());
        //}
    }//GEN-LAST:event_jrPerActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        
        StringBuffer hobi = new StringBuffer();
        StringBuffer kelamin = new StringBuffer();
        
        if(jrLaki.isSelected()) {
            kelamin.append(jrLaki.getText());
        }
        else {
            kelamin.append(jrPer.getText());
        }
        
        if(cbOlahraga.isSelected()) {
            if(cbJalan.isSelected()) {
                if(cbBaca.isSelected()) {
                    if(cbTidur.isSelected()) {
                        hobi.append("Olahraga, Jalan - Jalan, Membaca," + cbTidur.getText());
                    } else {
                        hobi.append("Olahraga, Jalan - Jalan, " + cbBaca.getText());
                    }
                } else {
                    if(cbTidur.isSelected()) {
                        hobi.append("Olahraga, Jalan - jalan, " + cbTidur.getText());
                    } else {
                        hobi.append("Olahraga, " + cbJalan.getText());
                    }
                }
            } else {
                if(cbBaca.isSelected()) {
                    if(cbTidur.isSelected()) {
                        hobi.append("Olahraga, Membaca, " + cbTidur.getText());
                    } else {
                        hobi.append("Olahraga, " + cbBaca.getText());
                    }
                } else {
                    if(cbTidur.isSelected()) {
                        hobi.append("Olahraga, " + cbTidur.getText());
                    } else {
                        hobi.append(cbOlahraga.getText());
                    }
                }
            }
        }
        
        else if(cbJalan.isSelected()) {
            if(cbBaca.isSelected()) {
                if(cbTidur.isSelected()) {
                    hobi.append("Jalan - jalan, Membaca, " + cbTidur.getText());
                } else {
                    hobi.append("Jalan - jalan, " + cbBaca.getText());
                }
            } else {
                if(cbTidur.isSelected()) {
                    hobi.append("Jalan - jalan, " + cbTidur.getText());
                } else {
                    hobi.append(cbJalan.getText());
                }
            }
        }
        
        else if(cbBaca.isSelected()) {
            if(cbTidur.isSelected()) {
                hobi.append("Membaca, "+cbTidur.getText());
            } else {
            hobi.append(cbBaca.getText());
            }
        }
        
        else if (cbTidur.isSelected()) {
            hobi.append(cbTidur.getText());
        }
        
        textHasil.setText("Nama : " + txtNama.getText() + "\n" + 
                "Lahir : " + txtLahir.getText() + "\n" +
                "Jenis Kelamin : " + kelamin + "\n" +
                "Hobi : " + hobi);
    }//GEN-LAST:event_btnOKActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasTigaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasTigaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasTigaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasTigaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasTigaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbBaca;
    private javax.swing.JCheckBox cbJalan;
    private javax.swing.JCheckBox cbOlahraga;
    private javax.swing.JCheckBox cbTidur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrLaki;
    private javax.swing.JRadioButton jrPer;
    private javax.swing.JTextArea textHasil;
    private javax.swing.JTextField txtLahir;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
